<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="iamPoatan" failures="5" tests="10" name="Runner.Registration" time="124.616" errors="0" timestamp="2024-02-29T04:43:45 IST" skipped="5">
  <testcase classname="Runner.Registration" name="runScenario" time="11.855">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="11.282">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="12.370">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="14.493">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="11.717">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="12.228">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="14.894">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="11.519">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="11.290">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="12.968">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.Registration -->
