<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="iamPoatan" failures="4" tests="9" name="Runner.Registration" time="105.036" errors="0" timestamp="2024-02-29T01:08:47 IST" skipped="4">
  <testcase classname="Runner.Registration" name="runScenario" time="11.008">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="12.676">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="11.767">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="10.785">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="10.545">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="10.812">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.Registration.the_user_clicks_on_register(Registration.java:123)
at ✽.the user clicks on register(file:///D:/demowebshop.tricentis.com/src/test/java/Features/RegistrationFeature.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="10.747">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="10.918">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.Registration" name="runScenario" time="15.778"/>
  <system-out/>
</testsuite> <!-- Runner.Registration -->
